// need to import
import almond from "../../Assets/almond.png";
import aptamilSlide from "../../Assets/bs-slide4.png";
import goYogurt from "../../Assets/go-yogurt.png";
import cashew from "../../Assets/cashew.png";
import chocoYogurt from "../../Assets/chocoolate-yogurt.png";
import suns from "../../Assets/suns.png";
import lays from "../../Assets/lays.png";
import greekYogurt from "../../Assets/best-seller-icecream.png";
import aptamilFront from "../../Assets/bs-slide1.png";
import veg1 from "../../Assets/veg1.png";
import veg2 from "../../Assets/veg2.png";
import veg3 from "../../Assets/veges-r.png";
import avocado from "../../Assets/avocado.png";
import avocado2 from "../../Assets/avocado2.png";
import potato from "../../Assets/basket-potato.png";
import berries from "../../Assets/berries.png";
import watermelon from "../../Assets/watermelon.png";
import papaya from "../../Assets/papaya.png";
import bearbrandS1 from "../../Assets/bearbrand.png";
import bearbrandS2 from "../../Assets/bearbrand-2.jpg";
import bearbrandS3 from "../../Assets/bearbrand-3.jpg";
import MartProfile from "../../Assets/mart-profile.jpg";
import MinisoProfile from "../../Assets/miniso-profile.jpg";
import OragonProfile from "../../Assets/oragon-profile.jpg";
import HomeProfile from "../../Assets/home-profile.jpg";

// Utility function to generate slugs from descriptions
const generateSlug = (description, id) => {
  return `${description
    .toLowerCase()
    .replace(/ /g, "-")
    .replace(/[^\w-]+/g, "")}-${id}`;
};

export const rawShopData = [
  {
    id: 1,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [bearbrandS1, bearbrandS2, bearbrandS3],
    topOption: ["840mg"],
    price: 312.34,
    discountPrice: null,
    discount: null,
    description: "Bear Brand Fortified Powdered Milk Drink 840g",
    slug: "",
    rating: 4,
    saleStatus: "Regular Price",
    productInfo: [
      "Ang BEAR BRAND® Fortified Powdered Milk Drink ang only powdered milk na NAPAG-ARALAN at NAPATUNAYAN na may kumpletong TIBAY-nutrients!",
      "Para sa growing kids.",
      "May Tibayng resistensya (100% Vitamin C, Iron and Zinc) at ngayon may Tibay ng katawan (100% Vit D, Protein and Calcium) nutrients pa",
      "Doble Tibay refers to Tibay-Resistensya nutrients and Tibay-Katawan nutrients with 3 balanced meals and exercise based on RENI needs of 3-5yo",
      "I-check ang expiration date sa likod ng pack. Basahin ang date base sa(MM/DD/YYYY).",
    ],
  },
  {
    id: 57,
    category: "Fresh Fruits",
    store: {
      name: "Miniso",
      profile: MinisoProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [avocado2, avocado, greekYogurt],
    topOption: ["100mg"],
    price: 60.01,
    discountPrice: null,
    discount: null,
    description:
      "Avocado Creamy Elegance Pure, Fresh, and Irresistibly Delicious",
    rating: 3,
    saleStatus: "Regular Price",
    productDetails: [],
  },
  {
    id: 2,
    category: "Vegetables",
    store: {
      name: "ARDCI Home",
      profile: HomeProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [veg3, almond, aptamilFront, suns, lays, watermelon],
    topOption: ["1kg"],
    price: 500.0,
    discountPrice: null,
    discount: null,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 3,
    category: "Vegetables",
    store: {
      name: "Oragon Shirt City",
      profile: OragonProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [veg2],
    topOption: ["150mg"],
    price: 150,
    discountPrice: 200,
    discount: -15,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 4,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [aptamilFront],
    topOption: ["150mg"],
    price: 600.12,
    discountPrice: 900,
    discount: -15,
    description: "Aptamil Gold+ ProNutra Biotik Stage 1 Infant Formula 31.7",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 5,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [almond],
    topOption: ["50mg"],
    price: 199.25,
    discountPrice: 250,
    discount: -10,
    description:
      "Sahale Snacks Maple Pecans Glazed Mix, Gluten-Free Snack, 4-Ounce Bag",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 6,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [lays],
    topOption: ["10mg"],
    price: 99.05,
    discountPrice: null,
    discount: null,
    description:
      "SunChips Minis, Garden Salsa Flavored Canister, Multigrain Chips, 3.75 oz Canister",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 7,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [papaya],
    topOption: ["120mg"],
    price: 90,
    discountPrice: null,
    discount: null,
    description: "Maxican Nature's Sweet Bounty Fresh Organic Giant Papaya",
    rating: 2,
    saleStatus: "Regular Price",
  },
  {
    id: 8,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [almond],
    topOption: ["Sweet", "Bitter"],
    price: [699, 799],
    discountPrice: null,
    discount: -23,
    description:
      "The Greek Gods Probiotic Plain Traditional Greek Yogurt, 32 oz",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 9,
    category: "Desserts",
    store: {
      name: "Miniso",
      profile: MinisoProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [goYogurt],
    topOption: ["375ml"],
    price: 99.0,
    discountPrice: 299,
    discount: -34,
    description: "Healthy Nuts Great Value Cashew Halves & Pieces",
    rating: 2,
    saleStatus: "Onsale",
  },
  {
    id: 10,
    category: "Desserts",
    store: {
      name: "Miniso",
      profile: MinisoProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [cashew],
    topOption: ["Sweet"],
    price: 59.0,
    discountPrice: 109,
    discount: -50,
    description: "Healthy Nuts Great Value Cashew Halves & Pieces",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 11,
    category: "Desserts",
    store: {
      name: "Miniso",
      profile: MinisoProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [aptamilSlide],
    topOption: ["250ml", "500ml"],
    price: [699, 799],
    discountPrice: null,
    discount: -15,
    description: "Aptamil Gold+ ProNuntra Biotik Stage 1 Infant Formnula-31.7",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 12,
    category: "Desserts",
    store: {
      name: "Miniso",
      profile: MinisoProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [chocoYogurt],
    topOption: ["Sweet"],
    price: 590.0,
    discountPrice: 890,
    discount: -20,
    description:
      "Oui by Yoplait Mocha & Chocolate Whole Milk Yogurt, French Style Yogurt Snack, 5 OZ Glass Yogurt Jar",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 13,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [greekYogurt],
    topOption: ["Chocolate"],
    price: 290.0,
    discountPrice: 590,
    discount: -65,
    description:
      "Oui by Yoplait Mocha & Chocolate Whole Milk Yogurt, French Style Yogurt Snack, 5 OZ Glass Yogurt Jar",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 14,
    category: "Desserts",
    store: {
      name: "Oragon Shirt City",
      profile: OragonProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [suns],
    topOption: ["50g", "120g"],
    price: [120, 150],
    discountPrice: null,
    discount: -23,
    description:
      "SunChips Minis, Garden Salsa Flavored Canister, Multigrain Chips, 3.75 oz Canister",
    rating: 4,
    saleStatus: "Onsale",
  },
  {
    id: 15,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [lays],
    topOption: ["50g", "120g"],
    price: [90, 120],
    discountPrice: null,
    discount: -15,
    description: "Delicious Lay's Potato Chips, Classic, 8 oz Bag",
    rating: 4,
    saleStatus: "Regular Price",
  },
  {
    id: 16,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [veg1],
    topOption: ["100mg"],
    price: 120,
    discountPrice: null,
    discount: null,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 3,
    saleStatus: "Regular Price",
  },
  {
    id: 17,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [veg3],
    topOption: ["1kg"],
    price: 500,
    discountPrice: null,
    discount: null,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 18,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [veg2],
    topOption: ["150mg"],
    price: 150,
    discountPrice: null,
    discount: null,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 19,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [aptamilFront],
    topOption: ["150mg"],
    price: 600,
    discountPrice: null,
    discount: null,
    description: "Aptamil Gold+ ProNutra Biotik Stage 1 Infant Formula 31.7",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 20,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [almond],
    topOption: ["50mg"],
    price: 199,
    discountPrice: null,
    discount: null,
    description:
      "Sahale Snacks Maple Pecans Glazed Mix, Gluten-Free Snack, 4-Ounce Bag",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 21,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [lays],
    topOption: ["10mg"],
    price: 99,
    discountPrice: null,
    discount: null,
    description:
      "SunChips Minis, Garden Salsa Flavored Canister, Multigrain Chips, 3.75 oz Canister",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 22,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [papaya],
    topOption: ["120mg"],
    price: 90,
    discountPrice: 95,
    discount: -5,
    description: "Maxican Nature's Sweet Bounty Fresh Organic Giant Papaya",
    rating: 2,
    saleStatus: "Onsale",
  },
  {
    id: 23,
    category: "Fresh Fruits",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [avocado],
    topOption: ["100mg"],
    price: 80,
    discountPrice: 100,
    discount: -12,
    description:
      "Avocado Creamy Elegance Pure, Fresh, and Irresistibly Delicious",
    rating: 1,
    saleStatus: "Onsale",
  },
  {
    id: 24,
    category: "Fresh Fruits",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [watermelon],
    topOption: ["275mg"],
    price: 150,
    discountPrice: 180,
    discount: -10,
    description: "Fresh and Sweet Watermelon Delights for Your Taste Buds!",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 25,
    category: "Fresh Fruits",
    store: {
      name: "ARDCI Home",
      profile: HomeProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [potato],
    topOption: ["375mg", "500mg", "1000mg"],
    price: [100.15, 250.23, 500.354],
    discount: -22,
    description:
      "Russet Idaho Potatoes Fresh Premium Fruit and Produce Vegetables, 4 pound case",
    rating: 4,
    saleStatus: "Onsale",
  },
  {
    id: 26,
    category: "Fresh Fruits",
    store: {
      name: "ARDCI Home",
      profile: HomeProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [papaya],
    topOption: ["120mg"],
    price: 90,
    discountPrice: 95,
    discount: -5,
    description: "Maxican Nature's Sweet Bounty Fresh Organic Giant Papaya",
    rating: 2,
    saleStatus: "Onsale",
  },
  {
    id: 27,
    category: "Fresh Fruits",
    store: {
      name: "ARDCI Home",
      profile: HomeProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [avocado2],
    topOption: ["100mg"],
    price: 60,
    discountPrice: 90,
    discount: -25,
    description:
      "Avocado Creamy Elegance Pure, Fresh, and Irresistibly Delicious",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 28,
    category: "Fresh Fruits",
    store: {
      name: "ARDCI Home",
      profile: HomeProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [berries],
    topOption: ["222g"],
    price: 120,
    discountPrice: 180,
    discount: -31,
    description:
      "Garden Fresh Juicy Grapes for a Burst of Sweetness in Every Bite",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 29,
    category: "Fresh Fruits",
    store: {
      name: "ARDCI Home",
      profile: HomeProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [avocado2],
    topOption: ["100mg"],
    price: 60.0,
    discountPrice: 90,
    discount: -25,
    description:
      "Avocado Creamy Elegance Pure, Fresh, and Irresistibly Delicious",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 30,
    category: "Vegetables",
    store: {
      name: "ARDCI Home",
      profile: HomeProfile,
      location: "ARCI Mart Bldg. Second Floor",
      contact: "+639123456789",
    },
    image: [veg3],
    topOption: ["1kg"],
    price: 500.0,
    discountPrice: null,
    discount: null,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 31,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [veg2],
    topOption: ["150mg"],
    price: 150,
    discountPrice: 200,
    discount: -15,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 32,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [aptamilFront],
    topOption: ["150mg"],
    price: 600,
    discountPrice: 900,
    discount: -15,
    description: "Aptamil Gold+ ProNutra Biotik Stage 1 Infant Formula 31.7",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 33,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [almond],
    topOption: ["50mg"],
    price: 199,
    discountPrice: 250,
    discount: -10,
    description:
      "Sahale Snacks Maple Pecans Glazed Mix, Gluten-Free Snack, 4-Ounce Bag",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 34,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [lays],
    topOption: ["10mg"],
    price: 99,
    discountPrice: null,
    discount: null,
    description:
      "SunChips Minis, Garden Salsa Flavored Canister, Multigrain Chips, 3.75 oz Canister",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 35,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [papaya],
    topOption: ["120mg"],
    price: 90,
    discountPrice: null,
    discount: null,
    description: "Maxican Nature's Sweet Bounty Fresh Organic Giant Papaya",
    rating: 2,
    saleStatus: "Regular Price",
  },
  {
    id: 36,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [almond],
    topOption: ["Sweet", "Bitter"],
    price: [120.0, 150.0],
    discountPrice: null,
    discount: -23,
    description:
      "The Greek Gods Probiotic Plain Traditional Greek Yogurt, 32 oz",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 37,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [goYogurt],
    topOption: ["375ml"],
    price: 99.0,
    discountPrice: 299,
    discount: -34,
    description: "Healthy Nuts Great Value Cashew Halves & Pieces",
    rating: 2,
    saleStatus: "Onsale",
  },
  {
    id: 38,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [cashew],
    topOption: ["Sweet"],
    price: 59.0,
    discountPrice: 109,
    discount: -50,
    description: "Healthy Nuts Great Value Cashew Halves & Pieces",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 39,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [aptamilSlide],
    topOption: ["250ml", "500ml"],
    price: [699, 799],
    discountPrice: null,
    discount: -15,
    description: "Healthy Nuts Great Value Cashew Halves & Pieces",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 40,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [chocoYogurt],
    topOption: ["Sweet"],
    price: 590.0,
    discountPrice: 890,
    discount: -20,
    description:
      "Oui by Yoplait Mocha & Chocolate Whole Milk Yogurt, French Style Yogurt Snack, 5 OZ Glass Yogurt Jar",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 41,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [greekYogurt],
    topOption: ["Chocolate"],
    price: 290.0,
    discountPrice: 590,
    discount: -65,
    description:
      "Oui by Yoplait Mocha & Chocolate Whole Milk Yogurt, French Style Yogurt Snack, 5 OZ Glass Yogurt Jar",
    rating: 5,
    saleStatus: "Onsale",
  },
  {
    id: 42,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [suns],
    topOption: ["50g", "120g"],
    price: 120,
    discountPrice: 20,
    discount: -23,
    description:
      "SunChips Minis, Garden Salsa Flavored Canister, Multigrain Chips, 3.75 oz Canister",
    rating: 4,
    saleStatus: "Onsale",
  },
  {
    id: 43,
    category: "Desserts",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [lays],
    topOption: ["50g", "120g"],
    price: 90,
    discountPrice: null,
    discount: null,
    description: "Delicious Lay's Potato Chips, Classic, 8 oz Bag",
    rating: 4,
    saleStatus: "Regular Price",
  },
  {
    id: 44,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [veg1],
    topOption: ["100mg"],
    price: 120,
    discountPrice: null,
    discount: null,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 3,
    saleStatus: "Regular Price",
  },
  {
    id: 45,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [veg3],
    topOption: ["1kg"],
    price: 500,
    discountPrice: null,
    discount: null,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 46,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [veg2],
    topOption: ["150mg"],
    price: 150,
    discountPrice: null,
    discount: null,
    description: "Whole Foods Market, Romaine Hearts Salad Bag Organic",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 47,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [aptamilFront],
    topOption: ["150mg"],
    price: 600,
    discountPrice: null,
    discount: null,
    description: "Aptamil Gold+ ProNutra Biotik Stage 1 Infant Formula 31.7",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 48,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [almond],
    topOption: ["50mg"],
    price: 199,
    discountPrice: null,
    discount: null,
    description:
      "Sahale Snacks Maple Pecans Glazed Mix, Gluten-Free Snack, 4-Ounce Bag",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 49,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [lays],
    topOption: ["10mg"],
    price: 99,
    discountPrice: null,
    discount: null,
    description:
      "SunChips Minis, Garden Salsa Flavored Canister, Multigrain Chips, 3.75 oz Canister",
    rating: 5,
    saleStatus: "Regular Price",
  },
  {
    id: 50,
    category: "Vegetables",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [papaya],
    topOption: ["120mg"],
    price: 90,
    discountPrice: 95,
    discount: -5,
    description: "Maxican Nature's Sweet Bounty Fresh Organic Giant Papaya",
    rating: 2,
    saleStatus: "Onsale",
  },
  {
    id: 51,
    category: "Fresh Fruits",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [avocado],
    topOption: ["100mg"],
    price: 80,
    discountPrice: 100,
    discount: -12,
    description:
      "Avocado Creamy Elegance Pure, Fresh, and Irresistibly Delicious",
    rating: 1,
    saleStatus: "Onsale",
  },
  {
    id: 52,
    category: "Ice Cream",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [watermelon],
    topOption: ["275mg"],
    price: 150,
    discountPrice: 180,
    discount: -10,
    description: "Fresh and Sweet Watermelon Delights for Your Taste Buds!",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 53,
    category: "Ice Cream",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [potato],
    topOption: ["375mg", "500mg"],
    price: [200, 300],
    discountPrice: null,
    discount: -22,
    description:
      "Russet Idaho Potatoes Fresh Premium Fruit and Produce Vegetables, 4 pound case",
    rating: 4,
    saleStatus: "Onsale",
  },
  {
    id: 54,
    category: "Fresh Fruits",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [papaya],
    topOption: ["120mg"],
    price: 90,
    discountPrice: 95,
    discount: -5,
    description: "Maxican Nature's Sweet Bounty Fresh Organic Giant Papaya",
    rating: 2,
    saleStatus: "Onsale",
  },
  {
    id: 55,
    category: "School Supplies",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [avocado2],
    topOption: ["100mg"],
    price: 60,
    discountPrice: 90,
    discount: -25,
    description:
      "Avocado Creamy Elegance Pure, Fresh, and Irresistibly Delicious",
    rating: 3,
    saleStatus: "Onsale",
  },
  {
    id: 56,
    category: "School Supplies",
    store: {
      name: "ARDCI Mart Grocery",
      profile: MartProfile,
      location: "ARCI Mart Bldg. First Floor",
      contact: "+639123456789",
    },
    image: [berries],
    topOption: ["222g"],
    price: 120,
    discountPrice: 180,
    discount: -31,
    description:
      "Garden Fresh Juicy Grapes for a Burst of Sweetness in Every Bite",
    rating: 5,
    saleStatus: "Onsale",
  },
];

// Add slug to each product dynamically and export shopData
export const shopData = rawShopData.map((product) => ({
  ...product,
  slug: generateSlug(product.description, product.id),
}));
